# Site settings
title: Jinki Lee
twitter_username: rob_hinds
name: Jinki Lee

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://operatingsystems.tistory.com
 - title: GitHub
   url: https://github.com/jinkilee
 - title: LinkedIn
   url: https://www.linkedin.com/in/jinki-lee-355546b1/

#Any buzzword skills you want to include
skills:
 - Python
 - Natural Language Processing
 - Computer Vision
 - Machine Learning
 - Java
 - C/C++

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Machine Learning Scientist
   start: 2019
   end: Ongoing
   employer: POSCO ICT
   description: I am performing AI/ML projects about different industrial areas which includes computer vision, anomaly detection and etc.
 - title: Data Scientist
   start: 2016
   end: 2019
   employer: AhnLab
   description: I performed R&D operation for building and deploying ML/AI model for automating SoC operation.
 - title: Security Engineer
   start: 2012
   end: 2015
   employer: AhnLab
   description: I performed 24/7 SoC operation for monitoring incoming cyber security attack and took an proper action according to the security policy. Also I managed different types of security devices and researched zero-day attacks for potential threat.

#Education is required
education:
 - level: Master of Science (MSc)
   date: 2015
   subject: Data Analytics
   school: University of Warwick
 - level: Bachelor of Science (B.Sc.)
   date: 2008
   subject: Computer Science
   school: SungKyunKwan University
 - level: Bachelor of Science (B.Sc.)
   date: 2006
   subject: Computer Science
   school: Kookmin Univeristy

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   profileurl: https://speakerdeck.com/robhinds
   talks:
    - title: Product Management for Engineers
      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
      conference: API Conference, Berlin 2018
    - title: Agile Machine Learning - from Theory to Production
      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - jinkilee/doodle
 - jinkilee/ieee
 - jinkilee/jigsaw
 - jinkilee/jinkilee.github.io

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/258813/rhinds
   flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
  I am a machine learning engineer from the POSCO ICT and performing AI/ML project for many different industry.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Python</strong>: python ...
   <strong>Machine Learning</strong>: ml ...
   <strong>Computer Vision</strong>: cv ...
   <strong>Natural Language Processing</strong>: nlp ...
   #<strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   #I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
   #As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
   #I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)

