# Site settings
title: Jinki Lee1
name: Jinki Li

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://www.google.com
 - title: GitHub
   url: https://www.google.com
 - title: StackOverflow
   url: https://www.google.com
 - title: DZone
   url: https://www.google.com
 - title: LinkedIn
   url: https://www.linkedin.com/in/jinki-lee-355546b1/

#Any buzzword skills you want to include
skills:
 - Scala
 - Akka-http
 - Microservices
 - Slick
 - Product management
 - API design
 - Groovy
 - Spring MVC/Boot/Social
 - Gradle
 - Java
 - JPA
 - SQL
 - REST
 - Technical Architecture
 - Machine learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json
